### PR TITLE
Add ps_spec

### PR DESCRIPTION
**Pull request by kkuzmin**
Add alps build

### CODE REVIEW

**Comment by kkuzmin** [comment]
test it

**Comment by kkuzmin** [comment]
test it

**Comment by kkuzmin** [comment]
test it

**Comment by joshm91** [comment]
Be aware that because this repo is a fork of a public repo it's also currently public which _probably_ isn't what you want 😬

**Comment by kkuzmin** [comment]
@joshm91 that is fine

**Comment by kkuzmin** [comment]
test it

**Pull request merged**
